
services:
  laravel:
    build: .
    container_name: laravel12_app
    ports:
      - "8080:80"             # Laravel accesible en http://localhost:8080
    volumes:
      - ./src:/var/www/html   # BIND VOLUME: c√≥digo en tu PC
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: laravel12_db
    ports:
      - "3307:3306"             # Laravel accesible en http://localhost:8080
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: laravel12_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8081:80"             # phpMyAdmin en http://localhost:8081
    depends_on:
      - db

volumes:
  db_data:
